version: "3.3"

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=datagreensystem
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=!dataGreenroot?0!D
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT=!dataGreenroot?0!D
      - PMA_HOST=mysql
    ports:
      - 8080:80
